# Generated by Django 4.0.3 on 2022-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
