# Generated by Django 4.0.3 on 2022-04-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensor_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_date', models.DateTimeField()),
                ('max_date', models.DateTimeField()),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visualization')),
            ],
        ),
    ]
