version: "3.2"
services:
#  redis:
#    restart: always
#    image: redis:5
#    ports:
#      - "6379:6379"
#    networks:
#      - db-net

  db:
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


  backend:
    restart: always
    container_name: back
    command : bash -c "python manage.py makemigrations && 
                      python manage.py migrate &&
                      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'password')" | python manage.py shell &&
                      python manage.py runserver"
#    env_file:
#     - ./project/settings.ini
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    restart: always
    command : npm start server
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

#networks:
#  db-net:
#    driver: bridge